src/Entity/ShopLocation.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="shop_location", indexes={@ORM\Index(name="external_id_idx", columns={"external_id"})})
 * @ORM\Entity(repositoryClass="App\Repository\ShopLocationRepository")
 * @ORM\HasLifecycleCallbacks
 */
class ShopLocation
{
    /** Timestampable trait */
    use Timestampable;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var Shop
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Shop", inversedBy="locations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $shop;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $name;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $externalId;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $brand;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $city;

    /**
     * @var float|null
     *
     * @ORM\Column(type="decimal", precision=11, scale=8, nullable=true)
     */
    private $lat;

    /**
     * @var float|null
     *
     * @ORM\Column(type="decimal", precision=11, scale=8, nullable=true)
     */
    private $lng;

    /**
     * @var array|string|null
     *
     * @ORM\Column(type="json", nullable=true)
     */
    private $details;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $tpLocationId;

    /**
     * @ORM\Column(type="decimal", precision=3, scale=2, nullable=true)
     */
    private $tpScore;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tpReviewsNo;

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->name;
    }

    /**
     * Get id.
     *
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * Set shop.
     *
     * @param Shop $shop
     * @return $this
     */
    public function setShop(Shop $shop)
    {
        $this->shop = $shop;

        return $this;
    }

    /**
     * Get shop.
     *
     * @return Shop
     */
    public function getShop()
    {
        return $this->shop;
    }

    /**
     * Set name.
     *
     * @param string|null $name
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string|null $externalId
     * @return $this
     */
    public function setExternalId(?string $externalId): self
    {
        $this->externalId = $externalId;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getExternalId(): ?string
    {
        return $this->externalId;
    }

    /**
     * @param string|null $slug
     * @return ShopLocation
     */
    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * Set brand.
     *
     * @param string|null $brand
     * @return $this
     */
    public function setBrand($brand)
    {
        $this->brand = $brand;

        return $this;
    }

    /**
     * Get brand.
     *
     * @return string|null
     */
    public function getBrand()
    {
        return $this->brand;
    }

    /**
     * Set city.
     *
     * @param string|null $city
     * @return $this
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city.
     *
     * @return string|null
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set lat.
     *
     * @param float|null $lat
     * @return $this
     */
    public function setLat($lat)
    {
        $this->lat = $lat;

        return $this;
    }

    /**
     * Get lat.
     *
     * @return float|null
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * Set lng.
     *
     * @param float|null $lng
     * @return $this
     */
    public function setLng($lng)
    {
        $this->lng = $lng;

        return $this;
    }

    /**
     * Get lng.
     *
     * @return float|null
     */
    public function getLng()
    {
        return $this->lng;
    }

    /**
     * Set details.
     *
     * @param array|string|null $details
     * @return $this
     */
    public function setDetails($details)
    {
        // If is string json then change to array
        if (!empty($details) && is_string($details) && $array = json_decode($details, true)) {
            $details = $array;
        }

        $this->details = $details;

        return $this;
    }

    /**
     * Get details as string.
     *
     * @return string|null
     */
    public function getDetails()
    {
        $details = $this->details;

        if (is_array($details)) {
            $details = json_encode($details);
        }

        return $details;
    }

    /**
     * Get details as array.
     *
     * @return array|null
     */
    public function getDetailsArray()
    {
        return $this->details;
    }
    
    /**
     * @return mixed
     */
    public function getTpLocationId()
    {
        return $this->tpLocationId;
    }
    
    /**
     * @param mixed $tpLocationId
     */
    public function setTpLocationId($tpLocationId): void
    {
        $this->tpLocationId = $tpLocationId;
    }
    
    /**
     * @return mixed
     */
    public function getTpScore()
    {
        return $this->tpScore;
    }
    
    /**
     * @param mixed $tpScore
     */
    public function setTpScore($tpScore): void
    {
        $this->tpScore = $tpScore;
    }
    
    /**
     * @return mixed
     */
    public function getTpReviewsNo()
    {
        return $this->tpReviewsNo;
    }
    
    /**
     * @param mixed $tpReviewsNo
     */
    public function setTpReviewsNo($tpReviewsNo): void
    {
        $this->tpReviewsNo = $tpReviewsNo;
    }
    
    

   
}

src/Controller/Admin/ShopController.php
<?php

namespace App\Controller\Admin;

use App\Entity\AttributeValue;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class ShopController
 *
 * @Route("/admin")
 */
class ShopController extends AbstractController
{
    /**
     * @Route("/attribute/{id}/values", name="app_admin_values_by_attribute", methods={"POST"}, requirements={"id"="\d+"})
     *
     * @param Request $request
     * @param int     $id
     * @return JsonResponse
     */
    public function getValuesByAttribute(Request $request, $id)
    {
        $data = [];

        $attributeValues = $this->getDoctrine()->getRepository(AttributeValue::class)->findBy([
            'attribute' => $id
        ]);

        foreach ($attributeValues as $attributeValue) {
            $data[] = [
                'id'    => $attributeValue->getId(),
                'name'  => $attributeValue->getName(),
                'image' => $attributeValue->getImageName(),
                'url'   => $attributeValue->getImageName()
                    ? $request->getUriForPath('/'.$this->getParameter('app.attribute_value.image.path').$attributeValue->getImageName())
                    : '',
            ];
        }

        return new JsonResponse($data);
    }
}

src/Controller/Web/ShopController.php
<?php

namespace App\Controller\Web;

use App\Entity\Attribute;
use App\Entity\Shop;
use App\Entity\ShopTemplate;
use App\Service\ShopService;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Twig\Environment;

/**
 * Class ShopController
 *
 * @package App\Controller\Web
 */
class ShopController extends AbstractController
{
    /** @var Environment */
    private $twig;

    /** @var ShopService */
    private $shopService;

    /**
     * ShopController constructor.
     *
     * @param Environment $twig
     * @param ShopService $shopService
     */
    public function __construct(Environment $twig, ShopService $shopService)
    {
        $this->twig = $twig;
        $this->shopService = $shopService;
    }

    /**
     * @Route("/{_locale}", defaults={"_locale": null}, requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"}, methods={"GET"}, name="app_web_shop_home")
     * @Route({
     *     "fr": "/fr/boutique",
     *     "en": "/en/shop",
     *     "nl": "/nl/winkel",
     *     "de": "/de/geschaft"
     * }, methods={"GET"}, name="app_web_voo_home")
     *
     * @param Request $request
     * @return Response
     */
    public function home(Request $request): Response
    {
        $shop = $this->getCurrentShop($request);
        $shopDomain = $this->getCurrentShopDomain($request);

        // Render Shop template if exists, otherwise base template
        $view = 'web/shop/'.$shop->getCode().'/home.html.twig';
        if (!$this->twig->getLoader()->exists($view)) {
            $view = 'web/base/home.html.twig';
        }

        $shopTemplateRepository = $this->getDoctrine()->getRepository(ShopTemplate::class);
        $templates = $shopTemplateRepository->getShopsByType($shop->getId(), Attribute::TYPE_PAGE_HOME);

        return $this->render($view, [
            'shop'            => $shop,
            'shopDomain'      => $shopDomain,
            'templates'       => $templates,
            'globalTemplates' => $shopTemplateRepository->getShopsByType($shop->getId(), Attribute::TYPE_GLOBAL, true),
            'data'            => $this->shopService->getHomeData($shop, $shopDomain, $templates),
        ]);
    }
    

    /**
     * @Route("/{_locale}/z/{countryCode}/{state}/{region}/{zipCode}/{city}",
     *     defaults={"_locale": null, "countryCode": null, "state": null, "region": null, "zipCode": null, "city": null},
     *     requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"},
     *     methods={"GET"},
     *     name="app_web_shop_home_redirect"
     * )
     *
     * @param Request $request
     * @return Response
     */
    public function homeRedirect(Request $request): Response
    {
        return $this->home($request);
    }
    
    /**
     * @Route("/{_locale}/filters", requirements={"_locale"="[a-z]{2}"}, methods={"GET"}, name="app_web_shop_filters")
     *
     * @param Request $request
     * @return Response
     */
    public function filters(Request $request): Response
    {
        
        $shop = $this->getCurrentShop($request);
        $shopDomain = $this->getCurrentShopDomain($request);
        
        // Render Shop template if exists, otherwise base template
        $view = 'web/shop/'.$shop->getCode().'/block/filters.html.twig';
        if (!$this->twig->getLoader()->exists($view)) {
            
            $view = 'web/block/map/filters/dynamic_checkbox.html.twig';
        }
        $language = $request->getLocale();
        
        $filters = $this->shopService->getFiltersData($shopDomain, $language);
    
        return $this->render($view, [
            
            'shop'            => $shop,
            'shopDomain'      => $shopDomain,
            'filters'         => $filters,
            
        ]);
        
    }

    /**
     * @Route("/{_locale}/{slug}", requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"}, methods={"GET"}, name="app_web_shop_show")
     * @Route("/{_locale}/s/carrefour/{slug}/{externalId}", requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"}, methods={"GET"}, name="app_web_carrefour_show")
     * @Route("/{_locale}/s/t/{slug}/{externalId}", requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"}, methods={"GET"}, name="app_web_carrefour_show_variant")
     * @Route("/{_locale}/pharma/{slug}/{externalId}", defaults={"externalId": null}, requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"}, methods={"GET"}, name="app_web_lloydspharma_show")
     * @Route({
     *     "fr": "/fr/boutique/{slug}",
     *     "en": "/en/shop/{slug}",
     *     "nl": "/nl/winkel/{slug}",
     *     "de": "/de/geschaft/{slug}"
     * }, methods={"GET"}, name="app_web_voo_show")
     * @Route({
     *     "fr": "/fr/s/moules-frites/{slug}/{externalId}",
     *     "en": "/en/s/{_localization}/{slug}/{externalId}"
     * }, defaults={"_localization": "mussels-fries"}, requirements={"_localization"="mussels-fries|Mussels and french fries"}, methods={"GET"}, name="app_web_leondebruxelles_show")
     *
     * @param Request     $request
     * @param string      $slug
     * @param string|null $externalId
     * @return Response
     */
    public function show(Request $request, string $slug, ?string $externalId = null): Response
    {
        $shop = $this->getCurrentShop($request);
        $shopDomain = $this->getCurrentShopDomain($request);

        // Render Shop template if exists, otherwise base template
        $view = 'web/shop/'.$shop->getCode().'/show.html.twig';
        if (!$this->twig->getLoader()->exists($view)) {
            $view = 'web/base/show.html.twig';
        }

        $shopTemplateRepository = $this->getDoctrine()->getRepository(ShopTemplate::class);

        return $this->render($view, [
            'shop'            => $shop,
            'shopDomain'      => $shopDomain,
            'templates'       => $shopTemplateRepository->getShopsByType($shop->getId(), Attribute::TYPE_PAGE_SHOW),
            'globalTemplates' => $shopTemplateRepository->getShopsByType($shop->getId(), Attribute::TYPE_GLOBAL, true),
            'location'        => $this->shopService->getShowData($shopDomain, $slug, $request->getLocale(), $externalId),
        ]);
    }

    /**
     * @Route("/{_locale}/s/{slug}", methods={"GET"}, name="app_web_shop_show_redirect")
     * @Route("/{_locale}/s/pharma/{slug}/{externalId}", defaults={"externalId": null}, requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"}, methods={"GET"}, name="app_web_lloydspharma_show_redirect")
     *
     *  @Route("/{_locale}/s/brasseurs/{slug}/{externalId}", defaults={"externalId": null}, requirements={"_locale"="[a-z]{2}(_[A-Z]{2})?"}, methods={"GET"}, name="app_web_les3brasseurs_show_redirect")
     * @param Request $request
     * @param string  $slug
     * @param string|null  $externalId
     * @return Response
     */
    public function showRedirect(Request $request, string $slug, ?string $externalId): Response
    {
        $shop = $this->getCurrentShop($request);

        switch ($shop->getCode()) {
            //in this case we need to handle the redirect
            case Shop::CODE_MEDIMARKET:
                $shopNewSlug = $this->shopService->getShopLocationSlugFromHistory($shop, $slug);

                if ($shopNewSlug) {
                    if ($request->getHost() == 'stores.pharmaclic.be') {
                        $url = $this->generateUrl('app_web_shop_show', ['slug' => $shopNewSlug]);

                        return $this->redirect('https://stores.medi-market.be'.$url, Response::HTTP_MOVED_PERMANENTLY);
                    }

                    return $this->redirectToRoute('app_web_shop_show', ['slug' => $shopNewSlug], Response::HTTP_MOVED_PERMANENTLY);
                }

                throw $this->createNotFoundException('This location does not exist');
                break;
                
            case Shop::CODE_LOLALIZA:
            case Shop::CODE_LOUISDELHAIZE:
            
                
                $shopNewSlug = $this->shopService->getShopLocationSlugFromHistory($shop, $slug);
    
                if ($shopNewSlug) {
                    return $this->redirectToRoute('app_web_shop_show', ['slug' => $shopNewSlug], Response::HTTP_MOVED_PERMANENTLY);
                }
    
                throw $this->createNotFoundException('This location does not exist');
                
                
                break;
                
            case Shop::CODE_LES3BRASSEURS:
    
                $slug = '3-brasseurs-'.$slug;
                
                $shopNewSlug = $this->shopService->getShopLocationSlugFromHistory($shop, $slug, $externalId);
    
                if ($shopNewSlug) {
                    return $this->redirectToRoute('app_web_shop_show', ['slug' => $shopNewSlug], Response::HTTP_MOVED_PERMANENTLY);
                }
    
                throw $this->createNotFoundException('This location does not exist');
                
                break;
    
            case Shop::CODE_LLOYDSPHARMA:
    
                $slug = 'pharma/'.$slug.'/'.$externalId;
    
                $shopNewSlug = $this->shopService->getShopLocationSlugFromHistory($shop, $slug);
    
                if ($shopNewSlug) {
                    return $this->redirectToRoute('app_web_lloydspharma_show', ['slug' => $shopNewSlug], Response::HTTP_MOVED_PERMANENTLY);
                }
                
                exit();
                break;
        }

        return $this->show($request, $slug);
    }
}

templates/web/shop/carrefour-be/home.html.twig
{% extends 'web/base/home.html.twig' %}

{% set assets = remote_assets(shop, carrefourHeaderUrl~app.request.locale~"/master.atoffernew.nolib.html", "assets") %}

{% if not app.request.get(constant('App\\Twig\\RoutingExtension::QUERY_NO_HEADER')) %}
    {% set noHeader = 0 %}
    {% if assets|length == 0 %}
        {% set  noHeader = 1 %}
    {% endif %}
{% else %}
    {% set noHeader = 1 %}
{% endif %}

{% set noHeader = 1 %}

{% if noHeader == 0 %}
    {# if there is no header add only class no-header #}
    {# if there is no red popup on top of header add class header-md #}
    {% set body_class = "header-md external-style" %}
{% else %}
    {% set body_class = "no-header" %}
{% endif %}


{% block body_class %}{{ body_class }}{% endblock %}

{% block header %}
    {% if noHeader == 0 %}
        {% autoescape false %}
            {{ remote_content(shop, carrefourHeaderUrl~app.request.locale~"/master.atoffernew.nolib.html", "header")  }}
        {% endautoescape %}
    {% endif %}
{% endblock %}

{% block footer %}
    {% if not app.request.get(constant('App\\Twig\\RoutingExtension::QUERY_NO_FOOTER')) %}
        {% include 'web/shop/' ~ shop.code ~ '/layout/footer.html.twig' %}
    {% endif %}
{% endblock %}

{% block content %}
    {# set filters content for map #}
    {% set twigData = {'filterContent': include('web/shop/' ~ shop.code ~ '/block/map/filter.html.twig')} %}

    {% include 'web/shop/' ~ shop.code ~ '/block/map.html.twig' %}
{% endblock %}

{% block stylesheets %}

    <link rel="stylesheet" type="text/css" media="all" href="https://cdn-mkt.be.carrefour.eu/free-html/oil_gdpr/design.css"/>
    {% if  noHeader == 0 %}
        {% for assetSrc in assets["css"]  %}
            <link rel="stylesheet" href="{{ assetSrc }}" type="text/css">
        {% endfor %}
    {% endif %}

    {{ encore_entry_link_tags('css/web/shop/' ~ shop.code ~ '/home') }}
{% endblock %}

{% block javascripts_var %}
    {{ parent() }}

    <script>
        var locale = '{{ app.request.locale }}';
    </script>

    <script type="text/javascript">
        globalData['openHoursData']['openClass'] = 'open';
        globalData['openHoursData']['closedClass'] = 'closed';
        globalData['brandSlugs'] = ['bio', 'easy', 'express', 'hyper', 'market'];

        var globalSettings = {
            language: "{{ app.request.locale }}",
            showMarkersClusterOnSearch: true,
            refreshControlCheckbox: false,
            fitBounce: true,
            map: {
                center: {lat: 50.62313744304004, lng: 5.365809522627387},
                zoom: 8,
                fitAll: true,
            },
            mapZoom: {position: 'right-bottom'},
            restriction: {
                latLngBounds: {north: 52.7, south: 48.03, east: 11.23, west: -1.96},
                strictBounds: true,
            },
            marker: {
                icon: '{{ asset('build/images/web/shop/' ~ shop.code ~ '/markers/marker-default.png') }}',
                icon_width: 50,
                icon_height: 53,
                icon_center: '{{ asset('build/images/web/block/map/marker/center.png') }}',
                icon_width_center: 30,
                icon_height_center: 30,
                icon_selected: '{{ asset('build/images/web/shop/' ~ shop.code ~ '/markers/marker-selected-default.png') }}',
                icon_width_selected: 75,
                icon_height_selected: 80,
            },
            marker_cluster: {
                images: '{{ asset('build/images/web/shop/' ~ shop.code ~ '/markers/m') }}',
                sizes: [{w: 52, h: 52}, {w: 55, h: 55}, {w: 65, h: 65}, {w: 77, h: 77}, {w: 89, h: 89}],
                textColor: '#ffffff',
            },
            autocompleteUrl: "{{ path('api_get_road_locations', {'version': shop.apiVersion})|escape('js') }}",
            geoLocationCountry: 'BE',
            query: {
                radius: 5000,
                onEmptyRadius: 15000,
            },
            styles: [
                {"featureType":"poi.business","stylers":[{"visibility":"off"}]},
                {"featureType":"poi.park","elementType":"labels.text","stylers":[{"visibility":"off"}]},
                {"featureType":"transit","stylers":[{"lightness":-10},{"visibility":"on"}]}
                ]
        };
    </script>
{% endblock %}

{% block before_body_end %}
    <div id="oil-preference-center" class="light as-oil"></div>
{% endblock %}

{% block head_scripts %}

    {% include 'web/shop/'~shop.code~'/block/tracking_top.html.twig' %}
    <script src="{{ carrefourTrackingScript }}" async></script>


{% endblock %}

{% block javascripts %}

    {{ encore_entry_script_tags('js/web/home') }}
    {{ encore_entry_script_tags('js/web/shop/' ~ shop.code ~ '/home') }}

    {{ encore_entry_script_tags('js/web/global/ga-events') }}

    {% if noHeader == 0 %}

        {% for assetSrc in assets["js"]  %}
            <script type="text/javascript" src="{{ assetSrc }}"></script>
        {% endfor %}

    {% endif %}



    {% include 'web/shop/'~shop.code~'/block/gdpr.html.twig' %}
    {% include 'web/shop/'~shop.code~'/block/tracking.html.twig' %}

{% endblock %}

templates/web/shop/carrefour-be/robots.txt.twig
{% if allowRobots %}

User-agent: *

# Allow search crawlers to discover the sitemap
Sitemap: {{ url_https('app_web_sitemap_locale_carrefour') }}

# Block access to specific groups of pages - Path

# Block CazoodleBot as it does not present correct accept content headers
User-agent: CazoodleBot
Disallow: /

# Block MJ12bot as it is just noise
User-agent: MJ12bot
Disallow: /

# Block dotbot as it cannot parse base urls properly
User-agent: dotbot/1.0
Disallow: /

# Block Gigabot
User-agent: Gigabot
Disallow: /


{% else %}
User-agent: *
Disallow: /
{% endif %}

templates/web/shop/carrefour-be/sitemap.xml.twig
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="https://www.w3.org/1999/xhtml"
        xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

    {% set currentDate = 'now'|date('Y-m-d') %}
    <url>
        <loc>{{ url_https('app_web_shop_home', {'_locale': app.request.locale}) }}</loc>
        <lastmod>{{ currentDate }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
    </url>

    {% for location in shopLocations %}
        {% set slug = location.detailsArray.slug %}
        {% if location.detailsArray.translatedSlug is defined %}
            {% for translatedSlug in location.detailsArray.translatedSlug %}
                {% if translatedSlug['language'] == app.request.locale %}
                    {% set slug = translatedSlug['value'] %}
                {% endif %}
            {% endfor %}
        {% endif %}

        <url>
            <loc>{{ url_https('app_web_carrefour_show', {'slug': slug, 'externalId': location.detailsArray.externalId}) }}</loc>
            <lastmod>{{ currentDate }}</lastmod>
            <changefreq>monthly</changefreq>
            <priority>0.5</priority>
        </url>
    {% endfor %}

</urlset>